// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

using App.SharedKernel;
using App.SharedKernel.Interfaces;

using Microsoft.EntityFrameworkCore;

#nullable disable

namespace App.Data.Models
{
    [Table("Log")]
    public partial class Log : BaseEntity, IAggregateRoot
    {
        [Key]
        public int Id { get; set; }
        public string Message { get; set; }
        public string Level { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Timestamp { get; set; }
        public string Exception { get; set; }
        public string LogEvent { get; set; }
        [StringLength(10)]
        public string EventType { get; set; }
    }
}